### ISSUE TITLE
[VITA-BOOTANIM] GIF loops forever

### ISSUE THREAD

**Issue by EntireCircus** [SKGleba/VitaTools#6]
As the title suggests, gif loops indefinitely, presumably even after bootup is complete (short pressing power button turns screen off but turning it back on still just shows the gif)

**Comment by SKGleba** [comment]
duplicate of https://github.com/SKGleba/VitaTools/issues/3

**Comment by SKGleba** [comment]
try the latest version (requires recompiling the animation or changing priority in boot animation settings)
