### ISSUE TITLE
Vita-Bootanim - Molecule boot logo

### ISSUE THREAD

**Issue by Rohenheim** [SKGleba/VitaTools#7]
when i start my vita, the molecule boot loog appears for half of a second before the logo of vita-bootanim, there's a way to take away that molecule logo?

**Comment by SKGleba** [comment]
Install enso_ex, delete ux0:eex/custom/bootlogo.raw and sync scripts via the enso_ex installer.
Example: https://youtu.be/y95IbldCISQ
